name: postgres
fqdn: postgres.tomunsworth.net
certificate: true
external_access: false
dedicated_ip:  false
container_environment: pi4
container_host: pi4
container_folder: postgres-pi4
update: false
