name: technitium-dns3
fqdn: dns3.tomunsworth.net
#defines the hosts that the container will be deployed onto
container_host: pi4
#defines the network the container will be deployed to
container_environment: technitium-dns3

# High-level flags for GitHub Actions orchestration
certificate: true             # needs Let's Encrypt cert
external_access: false         # should be exposed via Cloudflare Tunnel
dedicated_ip: true            # should get an IP from IP allocation CSV
update: false